In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import anndata
from scipy import io
from scipy.sparse import coo_matrix, csr_matrix
import os
pd.set_option('display.max_columns', None)

In [2]:
os.chdir('/media/MPEdge16/MM137/sc/py/py_out/')

In [3]:
X = io.mmread("/media/MPEdge16/MM137/sc/seurat/pbmc/RNA_assay_counts.mtx")

In [4]:
adata = anndata.AnnData(X = X.transpose().tocsr())

In [5]:
metadata = pd.read_csv("/media/MPEdge16/MM137/sc/seurat/pbmc/seurat_meta.csv")

In [6]:
with open("/media/MPEdge16/MM137/sc/seurat/pbmc/gene_names.csv", "r") as f:
    gene_names = f.read().splitlines()

In [7]:
adata.obs = metadata
adata.obs.index = adata.obs['barcode_2']
adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,percent_mito,barcode_1,lane,solo_X,solo_doublet,solo_singlet,solo_prediction,study_id,study_day,barcode_2
barcode_2,,,,,,,,,,,,,
AAACCTGAGACCTAGG-1,SeuratProject,2581,1005,0.387447,AAACCTGAGACCTAGG-1,MM-1,AAACCTGAGACCTAGG-1,-2.222334,1.723653,singlet,Sadie-018,SD1,AAACCTGAGACCTAGG-1
AAACCTGAGAGCCCAA-1,SeuratProject,1646,725,3.584447,AAACCTGAGAGCCCAA-1,MM-1,AAACCTGAGAGCCCAA-1,-5.264339,3.251961,singlet,Sadie-011,SD1,AAACCTGAGAGCCCAA-1
AAACCTGAGAGGTTGC-1,SeuratProject,4311,1966,3.757829,AAACCTGAGAGGTTGC-1,MM-1,AAACCTGAGAGGTTGC-1,-1.430171,0.703773,singlet,Sadie-011,SD1,AAACCTGAGAGGTTGC-1
AAACCTGAGAGTCGGT-1,SeuratProject,1764,959,2.040816,AAACCTGAGAGTCGGT-1,MM-1,AAACCTGAGAGTCGGT-1,-3.245542,1.475645,singlet,Sadie-018,SD1,AAACCTGAGAGTCGGT-1
AAACCTGAGATATGGT-1,SeuratProject,3794,1828,2.424881,AAACCTGAGATATGGT-1,MM-1,AAACCTGAGATATGGT-1,-0.240121,-0.074265,singlet,Sadie-018,SD1,AAACCTGAGATATGGT-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCATCGCATGGC-8,SeuratProject,4268,1818,2.085286,TTTGTCATCGCATGGC-1,MM-8,TTTGTCATCGCATGGC-1,-1.360806,1.416323,singlet,Sadie-016,SD2,TTTGTCATCGCATGGC-8
TTTGTCATCGGTCCGA-8,SeuratProject,2495,1065,0.721443,TTTGTCATCGGTCCGA-1,MM-8,TTTGTCATCGGTCCGA-1,-2.775678,3.856038,singlet,Sadie-036,SD3,TTTGTCATCGGTCCGA-8
TTTGTCATCTGATACG-8,SeuratProject,2782,1367,1.042416,TTTGTCATCTGATACG-1,MM-8,TTTGTCATCTGATACG-1,-2.887570,3.495042,singlet,Sadie-038,SD3,TTTGTCATCTGATACG-8
TTTGTCATCTGGCGAC-8,SeuratProject,3172,1128,1.134931,TTTGTCATCTGGCGAC-1,MM-8,TTTGTCATCTGGCGAC-1,-0.183614,0.856414,singlet,Sadie-036,SD3,TTTGTCATCTGGCGAC-8
TTTGTCATCTGTCTCG-8,SeuratProject,2766,1147,0.903832,TTTGTCATCTGTCTCG-1,MM-8,TTTGTCATCTGTCTCG-1,-3.180742,3.389316,singlet,Sadie-038,SD3,TTTGTCATCTGTCTCG-8

In [8]:
adata.var.index = gene_names

In [9]:
adata.write("mm_pbmc.h5ad")